# Generated by Django 2.0.4 on 2018-05-26 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='estado',
            field=models.CharField(default='1', max_length=2),
        ),
        migrations.AddField(
            model_name='persona',
            name='tiempo_registro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
