# Generated by Django 2.0.4 on 2018-05-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('nombres', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('descripcion_vida', models.TextField()),
                ('edad', models.IntegerField()),
                ('tiempo_registro', models.DateTimeField(auto_now=True)),
                ('cantidad_dinero', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
