# Generated by Django 2.0.4 on 2018-10-17 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaredes',
            name='idfb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebookdata', to='search.Facebook'),
        ),
        migrations.AlterField(
            model_name='personaredes',
            name='idgithub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='githubdata', to='search.Github'),
        ),
        migrations.AlterField(
            model_name='personaredes',
            name='idgoogle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='googledata', to='search.Google'),
        ),
        migrations.AlterField(
            model_name='personaredes',
            name='idinstagram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagramdata', to='search.Instagram'),
        ),
        migrations.AlterField(
            model_name='personaredes',
            name='idtw',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='twitterdata', to='search.Twitter'),
        ),
        migrations.AlterField(
            model_name='personaredes',
            name='idusuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariodata', to=settings.AUTH_USER_MODEL),
        ),
    ]
