# Generated by Django 2.0.4 on 2018-07-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebook',
            name='idfb',
            field=models.CharField(max_length=17, null=True, unique=True),
        ),
    ]
